# Generated by Django 3.0 on 2020-01-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Electronic', 'Electronic'), ('Hardware', 'Hardware'), ('Software', 'Software')], max_length=255)),
                ('availability', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=255)),
                ('price', models.FloatField()),
                ('img_url', models.ImageField(upload_to='images')),
            ],
        ),
    ]
