# Generated by Django 3.0 on 2020-01-02 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_ecommerce', '0002_auto_20200101_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Ecom-product'},
        ),
    ]
