# Generated by Django 3.0 on 2021-05-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('phone_number', models.PositiveIntegerField()),
                ('is_live', models.BooleanField()),
                ('amount', models.FloatField()),
            ],
        ),
    ]
