# Generated by Django 3.0 on 2021-05-28 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestModel',
            new_name='Test',
        ),
    ]
