# Generated by Django 3.0 on 2021-05-29 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0002_auto_20210528_2037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='TestModel',
        ),
    ]
